---
title: "Maps"
author: "Setu Mehta"
date: "11/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggmap)
library(gganimate)
library(ggthemes)
library(tidyverse)
library(janitor)
```

```{r}
# read in social distancing violations data

sd <- read_csv("../Data/311_Service_Requests_from_2010_to_Present.csv", 
               col_types = cols(
  .default = col_character(),
  `Unique Key` = col_double(),
  `Incident Zip` = col_double(),
  `Address Type` = col_logical(),
  `Facility Type` = col_logical(),
  `Due Date` = col_logical(),
  BBL = col_double(),
  `X Coordinate (State Plane)` = col_number(),
  `Y Coordinate (State Plane)` = col_number(),
  `Vehicle Type` = col_logical(),
  `Taxi Company Borough` = col_logical(),
  `Taxi Pick Up Location` = col_logical(),
  `Bridge Highway Name` = col_logical(),
  `Bridge Highway Direction` = col_logical(),
  `Road Ramp` = col_logical(),
  `Bridge Highway Segment` = col_logical(),
  Latitude = col_double(),
  Longitude = col_double()
)) %>%
  clean_names() %>%
  mutate(location_type = case_when(location_type == "Park/Playground" ~ "Park",
                          location_type == "Street/Sidewalk" ~ "Street",
                          location_type == "Street/Curbside" ~ "Street",
                          TRUE ~ location_type)) %>%
  remove_na() %>%
  select(latitude, longitude, borough, location_type, closed_date)

# Registering my API key

ggmap::register_google(key = "secret")

# Will create a map of NYC 

p <- ggmap(get_googlemap(center = c(lon = -73.935242, lat = 40.730610),
                    zoom = 10, scale = 2, size = c(640,640),
                    maptype = 'roadmap',
                    color = 'color'))

# Will plot social distancing violations into an animated map

graphic_sd <- p + geom_point(aes(x = longitude, y = latitude), 
                             data = sd, 
                             size = 0.5, 
                             alpha = .2) +
  ggthemes::theme_map(base_size = 12) +
  transition_manual(sd$location_type) +
  labs(title = "Reported Social Distancing Violations in New York City",
       subtitle = "Location: {current_frame}",
       caption = "Source: New York City Open 311 Data") +
  ggthemes::theme_map(base_size = 12)

# Saving the gif 

anim_save(filename = "violations.gif", animation = graphic_sd)

```

