
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(tidyr)
library(janitor)
library(lubridate)

```

```{r age, echo = FALSE}
age <- read_csv("Data/boroughs-by-age.csv",
      col_types = cols(.default = col_double(),
                       group = col_character()))
  
# It was difficult to work this data because the intial dataset was very wide.
# Therefore, I decided to make the data longer, whcih was difficult!

age_long <- pivot_longer(data = age, 
                         cols = -group, 
                         names_to = "county",
                         values_to = "count") %>% 
  separate(col = county, into = c("location", "type"), sep = "_", extra = "merge") %>%
  slice(1:150) %>%
  group_by(group, type, location) %>%
  summarize(av = mean(count), .groups = "drop") %>%
  arrange(location)

# Originally, I set extra = drop as I was getting an error. This error was
# occurring because there were multiple words separated by "_". By dropping the
# rest of the information past the first "_", I realized that I was losing
# valuable information. Using extra = merge will display all of the latter
# information and help me preserve crucial data.

# I worked with Ishan to understand how to split the column that had both the
# county and the type of test into two columns. I first tried to map an
# str_split function but that did not give me the result I wanted. Then, I
# learned about the separate function and tried to map it as well, which created
# an error. Then, I learned that the separate function does not need a map
# function!

saveRDS(age_long, file = "age_long.RDS")



```

```{r race, echo = FALSE}

sex <- read_csv("Data/boroughs-by-sex.csv",
      col_types = cols(.default = col_double(),
                       group = col_character()))
  
sex_long <- pivot_longer(data = sex, 
                         cols = -group, 
                         names_to = "county",
                         values_to = "count") %>% 
  separate(col = county, into = c("location", "type"), sep = "_", extra = "merge") %>%
  filter(group != "Boroughwide") %>%
  group_by(group, type, location) %>%
  summarize(av = mean(count), .groups = "drop") 

saveRDS(sex_long, file = "sex_long.RDS")

```

```{r race}

race <- read_csv("Data/boroughs-by-race.csv",
      col_types = cols(.default = col_double(),
                       group = col_character()))
  
race_long <- pivot_longer(data = race, 
                         cols = -group, 
                         names_to = "county",
                         values_to = "count") %>% 
  separate(col = county, into = c("location", "type"), sep = "_", extra = "merge") %>%
  group_by(group, type, location) %>%
  summarize(av = mean(count), .groups = "drop")

saveRDS(race_long, file = "race_long.RDS")

```

```{r merge}

joined_data <- full_join(age_long, race_long, by = c("group", "type", "location", "av")) %>%
  full_join(sex_long, by = c("group", "type", "location", "av"))

saveRDS(joined_data, file = "joined_data.RDS")

```


```{r 311_requests, echo = FALSE}

three <- read_csv("Data/311_Service_Requests_from_2010_to_Present.csv", col_types = cols(
  .default = col_character(),
  `Unique Key` = col_double(),
  `Incident Zip` = col_double(),
  `Address Type` = col_logical(),
  `Facility Type` = col_logical(),
  `Due Date` = col_logical(),
  BBL = col_double(),
  `X Coordinate (State Plane)` = col_number(),
  `Y Coordinate (State Plane)` = col_number(),
  `Vehicle Type` = col_logical(),
  `Taxi Company Borough` = col_logical(),
  `Taxi Pick Up Location` = col_logical(),
  `Bridge Highway Name` = col_logical(),
  `Bridge Highway Direction` = col_logical(),
  `Road Ramp` = col_logical(),
  `Bridge Highway Segment` = col_logical(),
  Latitude = col_double(),
  Longitude = col_double()
))

group_three <- three %>%
  clean_names() %>%
  select(created_date, location_type, incident_zip, borough, location) %>%
  filter(!is.na(location_type)) %>%
  filter(!is.na(borough)) %>%
  
# This decision to remove the NA's in the location_type column was just made to
# make the graph look better. I will need to reevaluate this decision in my
# final project.
  
  group_by(location_type, borough) %>%
  filter(borough != "Unspecified") %>%
  summarize(count = n(), .groups = "drop") %>%
  ggplot(aes(x = location_type, y = count, fill = borough)) +
  geom_col(position = "dodge") +
  labs(title = "Amount of Social Distancing Violations per\n Location and Borough",
       x = "Location",
       y = "Count") +
  coord_flip() +
  scale_fill_manual(name = "Borough",
                    values = c("#dde392","#afbe8f","#7d8570",
                               "#646f58","#504b3a"))

saveRDS(group_three, file = "group_three.RDS")
  
```

