---
title: "About"
output: html_fragment
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## About the Project 
I first became interested in studying trends regarding social distancing violations and COVID when I saw the significant impact that strict social distancing policies had on decreasing reported cases of COVID-19 in New York. As a proud New Yorker, I wanted to further explore the links between social distancing violations and COVID-19 statistics. New York City has a large repository of data available, such as 311 violations specific to social distancing, and COVID-19 related deaths, hospitalizations, and cases. I sought out to find if any links exists between these data.


## Information about data
My code can be found here: <https://github.com/setu-m/NYC_Covid_Data_Analysis>.
I downloaded the NYC COVID-19 data containing hospitalizations, deaths, and cases per NYC borough on 10-14-2020 used for my model from <https://github.com/nychealth/coronavirus-data>. This data further specifies information by race, age, and sex. I downloaded the 311 violations data from the NYC website used for my model on 10-14-2020 from <https://data.cityofnewyork.us/Social-Services/Social-Distancing-Violation-Reports-Mapped/jdvc-m64z>. I downloaded a filtered dataset from this site that just had social distancing violations in the past year.  


## About Me
My name is Setu and I am senior at Harvard College studying stem cell biology. You can reach me at setumehta@college.harvard.edu.